Repository lumawelhot/Luma-varaukset, pull requests merged in 2021-08, with the labels that each got.

#131 Documentation
  docs/img/book-event.png
  docs/img/book-visit.png
  docs/img/create-event.png
  docs/img/custom-form.png
  docs/img/event-list.png
  docs/img/event-page.png
  docs/img/extras.png
  docs/img/filtering.png
  docs/img/front-page.png
  docs/img/list-visit.png
  docs/img/modify-event.png
  docs/img/remove-events.png
  docs/img/users-list.png
  docs/user_guidelines.md
  frontend/public/index.html
  frontend/src/App.css
  frontend/src/components/Banner.js
Labels: documentation

#139 Custom emails
  backend/graphql/resolvers.js
  backend/graphql/typeDefs.js
  backend/models/email.js
  backend/setup.js
  backend/tests/cancelVisitLogic.test.js
  backend/tests/createVisitLogic.test.js
  backend/tests/deleteEvent.test.js
  backend/tests/event.test.js
  backend/tests/eventReservationLogic.test.js
  backend/tests/extra.test.js
  backend/tests/formExtras.test.js
  backend/tests/mailSender.test.js
  backend/tests/modifyEvent.test.js
  backend/tests/service.disabled.js
  backend/tests/user.test.js
  backend/tests/visit.test.js
  backend/utils/helpers.js
  backend/utils/importStaticData.js
  backend/utils/mailSender.js
  backend/utils/mongoinit.js
  frontend/src/App.js
  frontend/src/components/Custom/LumaEvent.js
  frontend/src/components/EmailConfig.js
  frontend/src/components/EventForm/Form.js
  frontend/src/components/ModifyEventModal/Form.js
  frontend/src/components/ModifyEventModal/Form.spec.js
  frontend/src/components/UserPage.js
  frontend/src/components/__snapshots__/UserPage.spec.js.snap
  frontend/src/graphql/queries.js
  frontend/src/locales/fi/common.json
  frontend/src/locales/fi/user.json
Labels: enhancement

#145 Event groups
  backend/graphql/resolvers.js
  backend/graphql/typeDefs.js
  backend/models/event.js
  backend/models/group.js
  backend/setup.js
  backend/tests/groupLogic.test.js
  backend/tests/testHelpers.js
  frontend/cypress/integration/tests/admin/admin.spec.js
  frontend/cypress/integration/tests/employee/employee.spec.js
  frontend/cypress/integration/tests/view/view.spec.js
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/MyCalendar.js
  frontend/src/components/EventForm/Form.js
  frontend/src/components/EventForm/index.js
  frontend/src/components/EventList.js
  frontend/src/components/GroupList.js
  frontend/src/components/ModifyEventModal/Form.js
  frontend/src/components/ModifyEventModal/index.js
  frontend/src/components/UserPage.js
  frontend/src/components/UserPage.spec.js
  frontend/src/components/VisitForm/index.js
  frontend/src/components/__snapshots__/UserPage.spec.js.snap
  frontend/src/graphql/queries.js
  frontend/src/locales/fi/common.json
  frontend/src/locales/fi/event.json
  frontend/src/locales/fi/user.json
Labels: enhancement

#157 Fix server pathnames
  .github/workflows/node-ci-push.yml
  Caddyfile
  backend/app.js
  docker-compose.yml
  frontend/cypress/integration/tests/employee.feature
  frontend/cypress/integration/tests/employee/employee.spec.js
  frontend/src/components/Custom/LumaEvent.js
  frontend/src/index.js
  initialize.sh
Labels: bug

#158 Csv feature
  docs/developer.md
  docs/user_guidelines.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/LoginForm.spec.js
  frontend/src/components/UserPage.js
  frontend/src/components/UserPage.spec.js
  frontend/src/components/VisitItem.spec.js
  frontend/src/components/VisitList.spec.js
  frontend/src/components/__snapshots__/UserPage.spec.js.snap
  frontend/src/graphql/queries.js
  frontend/src/helpers/csv.js
Labels: enhancement
